;;===========auto-complete-clang =====================
(add-to-list 'load-path "~/.emacs.d/plugin/auto-complete-1.3.1")
(add-to-list 'load-path "~/.emacs.d/plugin/auto-complete-clang/")
(require 'auto-complete-config)
;; (add-to-list 'ac-dictionary-directories (concat myoptdir "AC/ac-dict"))
(add-to-list 'ac-dictionary-directories "~/.emacs.d/plugin/auto-complete-1.3.1/ac-dict")

(require 'auto-complete-clang)

;; (setq ac-auto-start nil)
(setq ac-auto-start 1)
(setq ac-quick-help-delay 0.5)
;; (ac-set-trigger-key "TAB")
;; (define-key ac-mode-map  [(control tab)] 'auto-complete)
(define-key ac-mode-map  [(control tab)] 'auto-complete)
(defun my-ac-config ()
  (setq-default ac-sources '(ac-source-abbrev ac-source-dictionary ac-source-words-in-same-mode-buffers))
  (add-hook 'emacs-lisp-mode-hook 'ac-emacs-lisp-mode-setup)
  (add-hook 'c-mode-common-hook 'ac-cc-mode-setup)
  (add-hook 'c++-mode-common-hook 'ac-cc-mode-setup)
  ;; (add-hook 'ruby-mode-hook 'ac-ruby-mode-setup)
  ;; (add-hook 'css-mode-hook 'ac-css-mode-setup)
  (add-hook 'auto-complete-mode-hook 'ac-common-setup)
  (global-auto-complete-mode t))
(defun my-ac-cc-mode-setup ()
  (setq ac-sources (append '(ac-source-clang ac-source-yasnippet) ac-sources)))
(add-hook 'c-mode-common-hook 'my-ac-cc-mode-setup)
;; ac-source-gtags
;; (ac-config-default)
(my-ac-config)
;;=============auto-complete-clang end ==================
