;; 这里参考的原始版本 https://fanpengkong.com/2016/09/elisp-start/
(defun fpk-pelican-new-blog ()
  "Create a new pelican blog template"
  (interactive)
  (let ((cur-date (format-time-string "%Y-%m-%d"))
    (file-name (read-from-minibuffer "File Name: "))
    file-path
    my-buffer
    )
    (setq file-path (concat default-directory cur-date "-" file-name ".org"))
    (setq my-buffer (find-file file-path))
    (goto-char 1)
    (insert "#+TITLE: \n")
    (insert (format "#+DATE: %s\n" cur-date))
    (insert "#+CATEGORY: \n")
    (insert (format "#+AUTHOR: %s\n" user-full-name))
    (insert "#+PROPERTY: LANGUAGE en\n")
    (insert "#+PROPERTY: SUMMARY \n")
    (insert (format "#+PROPERTY: SLUG %s\n" file-name))
    (insert "#+PROPERTY: MODIFIED \n")
    (insert "#+PROPERTY: TAGS \n")
    (insert "#+PROPERTY: SAVE_AS \n\n")
    (insert "#+PROPERTY: eval never\n")
    (insert "#+OPTIONS: toc:nil num:nil ^:nil\n\n")
    (goto-char (point-min))
    (end-of-line)
    ))
